In [12]:
import pandas as pd


data_A = pd.read_json("../data_raw/dados_empresaA.json")
data_B = pd.read_csv("../data_raw/dados_empresaB.csv")

In [19]:
data_A.head(5)

,Nome do Produto,Categoria do Produto,Preço do Produto (R$),Quantidade em Estoque,Filial
0,Blush em pó,Eletrodomésticos,79.41,7,Filial 7
1,Lápis de sobrancelha,Eletrodomésticos,85.47,78,Filial 8
2,Base líquida,Roupas,75.02,34,Filial 8
3,Base líquida,Roupas,44.94,90,Filial 10
4,Lápis de sobrancelha,Alimentos,58.63,91,Filial 7

In [20]:
data_B.head()

,Nome do Item,Classificação do Produto,Valor em Reais (R$),Quantidade em Estoque,Nome da Loja,Data da Venda
0,Lápis de sobrancelha,Roupas,55.17,62,Filial 1,2023-04-13 18:58:06.794203
1,Batom matte,Eletrônicos,74.15,48,Filial 9,2023-06-03 18:58:06.794203
2,Corretivo,Roupas,54.86,36,Filial 5,2023-06-08 18:58:06.794203
3,Delineador líquido,Roupas,91.29,1,Filial 8,2023-02-27 18:58:06.794203
4,Batom líquido,Roupas,44.65,52,Filial 2,2022-09-05 18:58:06.794203

In [ ]:
#padronizar 'Nome do produto' e 'Nome do Item'
#padronizar 'Preço do Produto (R$) e 'Valor em Reais (R$)
#dropar coluna 'Data da venda' 
#padronizar 'Nome da loja' e 'Filial'

In [29]:
data_processed = pd.read_csv("../data_processed/dados_combinados.csv")
data_processed_ordedby_filial = data_processed.sort_values(by='Filial')
data_processed_ordedby_filial.head()

,Nome do Produto,Categoria do Produto,Preço do Produto (R$),Quantidade em Estoque,Filial,Data da Venda
1609,Batom matte,Roupas,95.08,24,Filial 1,Indisponivel
4154,Máscara de cílios,Eletrônicos,41.16,57,Filial 1,2023-05-20 18:58:06.794203
728,Máscara de cílios,Roupas,40.61,3,Filial 1,Indisponivel
735,Sombra de olhos,Eletrônicos,26.45,98,Filial 1,Indisponivel
743,Pó compacto,Alimentos,98.51,39,Filial 1,Indisponivel